#!/usr/bin/env bash

# 

# arch-recover.sh — Finish what phase 3 didn’t.

# 

# Idempotent: run as many times as you need. Skips anything already done.

# Run this as your normal user, NOT as root.

set -uo pipefail

GREEN=’\033[1;32m’; YELLOW=’\033[1;33m’; RED=’\033[1;31m’; CYAN=’\033[1;36m’; RESET=’\033[0m’
log()  { printf “${GREEN}[+]${RESET} %s\n” “$*”; }
warn() { printf “${YELLOW}[!]${RESET} %s\n” “$*”; }
err()  { printf “${RED}[x]${RESET} %s\n” “$*”; }
hr()   { printf “${CYAN}──────────────────────────────────────────────${RESET}\n”; }

[[ $EUID -eq 0 ]] && { err “Run as your user, not root.”; exit 1; }

hr
log “Starting recovery…”
hr

# ── 1. oh-my-zsh + plugins ──────────────────────────────────────────────────

if [[ ! -d “$HOME/.oh-my-zsh” ]]; then
log “Installing oh-my-zsh (unattended)…”
sh -c “$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)” “” –unattended –keep-zshrc
else
log “oh-my-zsh already present — skipping.”
fi

CUSTOM=”${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}”
if [[ ! -d “$CUSTOM/plugins/zsh-autosuggestions” ]]; then
log “Cloning zsh-autosuggestions…”
git clone –depth=1 https://github.com/zsh-users/zsh-autosuggestions “$CUSTOM/plugins/zsh-autosuggestions”
fi
if [[ ! -d “$CUSTOM/plugins/zsh-syntax-highlighting” ]]; then
log “Cloning zsh-syntax-highlighting…”
git clone –depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git “$CUSTOM/plugins/zsh-syntax-highlighting”
fi

# ── 2. .zshrc with pywal + plugins ──────────────────────────────────────────

if [[ ! -f “$HOME/.zshrc” ]] || ! grep -q “zsh-autosuggestions” “$HOME/.zshrc” 2>/dev/null; then
log “Writing .zshrc…”
cat > “$HOME/.zshrc” <<‘ZSHRC’
export ZSH=”$HOME/.oh-my-zsh”
ZSH_THEME=“agnoster”
plugins=(git sudo command-not-found z fzf docker docker-compose npm node python pip
zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

[ -f “$HOME/.cache/wal/sequences” ] && cat “$HOME/.cache/wal/sequences”
[ -f “$HOME/.cache/wal/colors-tty.sh” ] && source “$HOME/.cache/wal/colors-tty.sh”

export EDITOR=nvim
export VISUAL=nvim
alias v=nvim
alias vi=nvim
alias ll=‘eza -lah –icons –git’
alias ls=‘eza –icons’
alias cat=‘bat –paging=never’
alias cd=‘z’
command -v zoxide >/dev/null && eval “$(zoxide init zsh)”

export PATH=”$HOME/.local/bin:$PATH”
ZSHRC
else
log “.zshrc already configured — skipping.”
fi

# ── 3. python-pywalfox (AUR — script may have skipped this) ─────────────────

if ! command -v pywalfox >/dev/null 2>&1; then
log “Installing python-pywalfox via paru…”
paru -S –needed –noconfirm python-pywalfox || warn “pywalfox install failed — Firefox theming won’t work, continuing.”
else
log “pywalfox already installed.”
fi

# ── 4. LazyVim with language extras ─────────────────────────────────────────

if [[ ! -d “$HOME/.config/nvim” ]] || [[ -z “$(ls -A “$HOME/.config/nvim” 2>/dev/null)” ]]; then
log “Bootstrapping LazyVim…”
mkdir -p “$HOME/.config/nvim”
git clone –depth=1 https://github.com/LazyVim/starter “$HOME/.config/nvim”
rm -rf “$HOME/.config/nvim/.git”
cat > “$HOME/.config/nvim/lua/plugins/extras.lua” <<‘LUA’
return {
{ import = “lazyvim.plugins.extras.lang.typescript” },
{ import = “lazyvim.plugins.extras.lang.json” },
{ import = “lazyvim.plugins.extras.lang.yaml” },
{ import = “lazyvim.plugins.extras.lang.toml” },
{ import = “lazyvim.plugins.extras.lang.markdown” },
{ import = “lazyvim.plugins.extras.lang.python” },
{ import = “lazyvim.plugins.extras.lang.rust” },
{ import = “lazyvim.plugins.extras.lang.go” },
{ import = “lazyvim.plugins.extras.lang.php” },
{ import = “lazyvim.plugins.extras.lang.tailwind” },
{ import = “lazyvim.plugins.extras.lang.docker” },
{ import = “lazyvim.plugins.extras.lang.git” },
{ import = “lazyvim.plugins.extras.lang.sql” },
{ import = “lazyvim.plugins.extras.lang.bash” },
{ import = “lazyvim.plugins.extras.editor.harpoon2” },
{ import = “lazyvim.plugins.extras.formatting.prettier” },
{ import = “lazyvim.plugins.extras.linting.eslint” },
}
LUA
log “Running headless Lazy sync (3-5 min)…”
nvim –headless ‘+Lazy! sync’ +qa || warn “Lazy sync had errors — non-fatal.”
else
log “nvim config exists — skipping.”
fi

# ── 5. Themed hyprland.conf (BACKING UP THE CURRENT ONE) ────────────────────

HYPR_CONF=”$HOME/.config/hypr/hyprland.conf”
if [[ -f “$HYPR_CONF” ]] && grep -q “AUTOGENERATED HYPRLAND CONFIG” “$HYPR_CONF” 2>/dev/null; then
log “Backing up default hyprland.conf to hyprland.conf.default…”
cp “$HYPR_CONF” “$HOME/.config/hypr/hyprland.conf.default”
fi

mkdir -p “$HOME/.config/hypr”
log “Writing themed hyprland.conf…”
cat > “$HYPR_CONF” <<‘HYPR’

# ── Themed Hyprland config (recovery) ──────────────────────────────────────

monitor=,preferred,auto,1

$mod  = SUPER
$term = kitty
$menu = rofi -show drun

source = ~/.cache/wal/colors-hyprland.conf

input {
kb_layout = us
follow_mouse = 1
touchpad { natural_scroll = true }
sensitivity = 0
}

general {
gaps_in = 4
gaps_out = 8
border_size = 2
col.active_border = $color4 $color6 45deg
col.inactive_border = $color0
layout = dwindle
}

decoration {
rounding = 8
blur { enabled = true; size = 6; passes = 2; new_optimizations = true }
shadow { enabled = true; range = 12; render_power = 3 }
}

animations {
enabled = true
bezier  = ease,0.05,0.9,0.1,1.0
animation = windows,    1, 5, ease
animation = fade,       1, 5, ease
animation = workspaces, 1, 5, ease
}

dwindle { pseudotile = true; preserve_split = true }
misc    { disable_hyprland_logo = true; force_default_wallpaper = 0 }

# Autostart

exec-once = swww-daemon
exec-once = sleep 1 && swww img ~/Pictures/wallpapers/default.jpg –transition-type any
exec-once = wal -R
exec-once = waybar
exec-once = mako
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste –type text  –watch cliphist store
exec-once = wl-paste –type image –watch cliphist store
exec-once = nm-applet –indicator
exec-once = blueman-applet
exec-once = hypridle

# Keybinds

bind = $mod, Return, exec, $term
bind = $mod, Q, killactive
bind = $mod SHIFT, E, exit
bind = $mod, E, exec, thunar
bind = $mod, R, exec, $menu
bind = $mod, V, togglefloating
bind = $mod, F, fullscreen
bind = $mod, P, pseudo
bind = $mod, J, togglesplit
bind = $mod, L, exec, hyprlock

bind = $mod, left,  movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up,    movefocus, u
bind = $mod, down,  movefocus, d

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bind = , Print,         exec, grim -g “$(slurp)” - | swappy -f -
bind = SHIFT, Print,    exec, grim - | swappy -f -

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute,        exec, wpctl set-mute   @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86MonBrightnessUp,   exec, brightnessctl s 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
bindl  = , XF86AudioPlay, exec, playerctl play-pause
bindl  = , XF86AudioNext, exec, playerctl next
bindl  = , XF86AudioPrev, exec, playerctl previous
HYPR

# ── 6. hyprlock + hypridle ──────────────────────────────────────────────────

if [[ ! -f “$HOME/.config/hypr/hyprlock.conf” ]]; then
log “Writing hyprlock.conf…”
cat > “$HOME/.config/hypr/hyprlock.conf” <<‘EOF’
source = ~/.cache/wal/colors-hyprland.conf
background {
monitor =
path    = ~/Pictures/wallpapers/default.jpg
blur_passes = 2
}
input-field {
monitor =
size    = 240, 50
position = 0, -120
halign = center
valign = center
outline_thickness = 2
outer_color = $color4
inner_color = $color0
font_color  = $color7
fade_on_empty = true
placeholder_text = <i>Password…</i>
}
label {
monitor =
text = cmd[update:1000] echo “$(date +”%H:%M”)”
font_size = 90
position = 0, 200
halign = center
valign = center
color = $color7
}
EOF
fi

if [[ ! -f “$HOME/.config/hypr/hypridle.conf” ]]; then
log “Writing hypridle.conf…”
cat > “$HOME/.config/hypr/hypridle.conf” <<‘EOF’
general {
lock_cmd = pidof hyprlock || hyprlock
before_sleep_cmd = loginctl lock-session
after_sleep_cmd = hyprctl dispatch dpms on
}
listener { timeout = 300;  on-timeout = brightnessctl -s set 10; on-resume = brightnessctl -r }
listener { timeout = 600;  on-timeout = loginctl lock-session }
listener { timeout = 660;  on-timeout = hyprctl dispatch dpms off; on-resume = hyprctl dispatch dpms on }
listener { timeout = 1800; on-timeout = systemctl suspend }
EOF
fi

# ── 7. Kitty ────────────────────────────────────────────────────────────────

mkdir -p “$HOME/.config/kitty”
if [[ ! -f “$HOME/.config/kitty/kitty.conf” ]]; then
log “Writing kitty.conf…”
cat > “$HOME/.config/kitty/kitty.conf” <<‘EOF’
font_family      JetBrainsMono Nerd Font
font_size        12
enable_audio_bell no
window_padding_width 8
confirm_os_window_close 0
background_opacity 0.92

include ~/.cache/wal/colors-kitty.conf

map ctrl+shift+enter new_window
map ctrl+shift+t     new_tab
map ctrl+shift+w     close_window
EOF
fi

# ── 8. Rofi ─────────────────────────────────────────────────────────────────

mkdir -p “$HOME/.config/rofi”
if [[ ! -f “$HOME/.config/rofi/config.rasi” ]]; then
log “Writing rofi config…”
cat > “$HOME/.config/rofi/config.rasi” <<‘EOF’
@theme “~/.cache/wal/colors-rofi-dark.rasi”
configuration {
modi: “drun,run,window”;
show-icons: true;
font: “JetBrainsMono Nerd Font 11”;
display-drun: “ “;
display-run:  “ “;
display-window: “ “;
}
EOF
fi

# ── 9. Waybar ───────────────────────────────────────────────────────────────

mkdir -p “$HOME/.config/waybar”
if [[ ! -f “$HOME/.config/waybar/config.jsonc” ]]; then
log “Writing waybar config…”
cat > “$HOME/.config/waybar/config.jsonc” <<‘EOF’
{
“layer”: “top”,
“position”: “top”,
“height”: 32,
“spacing”: 4,
“modules-left”:   [“hyprland/workspaces”, “hyprland/window”],
“modules-center”: [“clock”],
“modules-right”:  [“tray”, “pulseaudio”, “network”, “cpu”, “memory”, “battery”],
“hyprland/workspaces”: {
“format”: “{icon}”,
“format-icons”: { “active”: “●”, “default”: “○” },
“on-click”: “activate”
},
“hyprland/window”: { “max-length”: 50 },
“clock”: {
“format”:          “ {:%H:%M}”,
“format-alt”:      “ {:%a %Y-%m-%d %H:%M}”,
“tooltip-format”:  “<tt><small>{calendar}</small></tt>”
},
“cpu”:      { “format”: “ {usage}%”, “interval”: 5 },
“memory”:   { “format”: “ {percentage}%”, “interval”: 5 },
“network”: {
“format-wifi”:         “ {essid}”,
“format-ethernet”:     “ connected”,
“format-disconnected”: “⚠ off”,
“tooltip-format”:      “{ifname}: {ipaddr}”
},
“pulseaudio”: {
“format”:         “{icon} {volume}%”,
“format-muted”:   “ muted”,
“format-icons”:   { “default”: [””, “”, “”] },
“on-click”:       “pavucontrol”,
“scroll-step”:    5
},
“battery”: {
“states”:          { “warning”: 30, “critical”: 15 },
“format”:          “{icon} {capacity}%”,
“format-charging”: “  {capacity}%”,
“format-plugged”:  “ {capacity}%”,
“format-icons”:    [””, “”, “”, “”, “”]
},
“tray”: { “icon-size”: 18, “spacing”: 8 }
}
EOF
fi

if [[ ! -f “$HOME/.config/waybar/style.css” ]]; then
log “Writing waybar style.css…”
cat > “$HOME/.config/waybar/style.css” <<EOF
@import “$HOME/.cache/wal/colors-waybar.css”;

- {
  border: none;
  border-radius: 0;
  font-family: “JetBrainsMono Nerd Font”, monospace;
  font-size: 13px;
  min-height: 0;
  }

window#waybar {
background: alpha(@background, 0.85);
color: @foreground;
}

#workspaces button {
padding: 0 10px;
background: transparent;
color: @color8;
border-bottom: 2px solid transparent;
}
#workspaces button.active {
color: @foreground;
border-bottom: 2px solid @color4;
}

#window, #clock, #cpu, #memory, #network, #pulseaudio, #battery, #tray {
padding: 0 12px;
color: @foreground;
}

#battery.warning  { color: @color3; }
#battery.critical { color: @color1; }
EOF
fi

# ── 10. Wallpaper (if missing) ──────────────────────────────────────────────

mkdir -p “$HOME/Pictures/wallpapers”
if [[ ! -f “$HOME/Pictures/wallpapers/default.jpg” ]]; then
log “Generating fallback wallpaper…”
if command -v convert >/dev/null 2>&1; then
convert -size 1920x1080 gradient:’#1a1b26-#414868’ “$HOME/Pictures/wallpapers/default.jpg” || true
fi
fi

# Re-seed pywal against the wallpaper so colors-waybar.css etc. exist

if [[ -f “$HOME/Pictures/wallpapers/default.jpg” ]]; then
log “Re-seeding pywal…”
wal -i “$HOME/Pictures/wallpapers/default.jpg” -n -s -t -e -q || warn “pywal seed had issues”
fi

# Firefox theming bridge (best effort)

if command -v pywalfox >/dev/null 2>&1; then
pywalfox install >/dev/null 2>&1 || true
pywalfox update  >/dev/null 2>&1 || true
fi

hr
log “Recovery done.”
log “Now reload Hyprland to pick up the new config:”
log “    hyprctl reload”
log “”
log “Or, if reload doesn’t bring up Waybar, fully restart Hyprland:”
log “  1) Switch to TTY:  Ctrl+Alt+F2”
log “  2) Log in as daniel”
log “  3) pkill Hyprland”
log “  4) tuigreet returns; pick Hyprland; log in”
hr