local json_path = vim.fn.expand("~/.cache/wal/colors.json")
local ok, raw = pcall(vim.fn.readfile, json_path)
if not ok then return end
local ok2, pal = pcall(vim.json.decode, table.concat(raw, "\n"))
if not ok2 then return end

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "alchemia"

local c = pal.colors
local s = pal.special

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Core
hi("Normal",          { fg = s.foreground, bg = s.background })
hi("NormalFloat",     { fg = s.foreground, bg = c.color8 })
hi("NormalNC",        { fg = s.foreground, bg = s.background })
hi("CursorLine",      { bg = c.color8 })
hi("CursorColumn",    { bg = c.color8 })
hi("ColorColumn",     { bg = c.color8 })
hi("LineNr",          { fg = c.color8 })
hi("CursorLineNr",    { fg = c.color11, bold = true })
hi("SignColumn",      { fg = c.color8, bg = s.background })
hi("VertSplit",       { fg = c.color8, bg = s.background })
hi("WinSeparator",    { fg = c.color8, bg = s.background })
hi("StatusLine",      { fg = s.foreground, bg = c.color8 })
hi("StatusLineNC",    { fg = c.color7, bg = c.color0 })
hi("TabLine",         { fg = c.color7, bg = c.color8 })
hi("TabLineSel",      { fg = s.foreground, bg = s.background })
hi("TabLineFill",     { bg = c.color0 })
hi("EndOfBuffer",     { fg = c.color8 })
hi("Folded",          { fg = c.color8, italic = true })
hi("FoldColumn",      { fg = c.color8 })

-- Syntax
hi("Comment",         { fg = c.color8, italic = true })
hi("Constant",        { fg = c.color3 })
hi("String",          { fg = c.color2 })
hi("Character",       { fg = c.color2 })
hi("Number",          { fg = c.color3 })
hi("Boolean",         { fg = c.color5 })
hi("Float",           { fg = c.color3 })
hi("Identifier",      { fg = s.foreground })
hi("Function",        { fg = c.color4 })
hi("Statement",       { fg = c.color1 })
hi("Conditional",     { fg = c.color1 })
hi("Repeat",          { fg = c.color1 })
hi("Label",           { fg = c.color3 })
hi("Keyword",         { fg = c.color5 })
hi("Operator",        { fg = c.color6 })
hi("Exception",       { fg = c.color1 })
hi("PreProc",         { fg = c.color5 })
hi("Include",         { fg = c.color5 })
hi("Define",          { fg = c.color5 })
hi("Type",            { fg = c.color3 })
hi("StorageClass",    { fg = c.color5 })
hi("Structure",       { fg = c.color5 })
hi("Typedef",         { fg = c.color3 })
hi("Special",         { fg = c.color6 })
hi("SpecialChar",     { fg = c.color6 })
hi("Delimiter",       { fg = c.color7 })
hi("Underlined",      { fg = c.color4, underline = true })
hi("Bold",            { bold = true })
hi("Italic",          { italic = true })
hi("Error",           { fg = c.color1, bold = true })
hi("Todo",            { fg = c.color11, bold = true })

-- UI
hi("Pmenu",           { fg = s.foreground, bg = c.color8 })
hi("PmenuSel",        { fg = c.color0, bg = c.color4 })
hi("PmenuSbar",       { bg = c.color8 })
hi("PmenuThumb",      { bg = c.color4 })
hi("Search",          { fg = c.color0, bg = c.color11 })
hi("IncSearch",       { fg = c.color0, bg = c.color3, bold = true })
hi("CurSearch",       { fg = c.color0, bg = c.color11, bold = true })
hi("Visual",          { bg = c.color8 })
hi("VisualNOS",       { bg = c.color8 })
hi("MatchParen",      { fg = c.color11, bold = true })
hi("WildMenu",        { fg = c.color0, bg = c.color4 })
hi("Question",        { fg = c.color2 })
hi("MoreMsg",         { fg = c.color2 })
hi("ModeMsg",         { fg = s.foreground, bold = true })
hi("ErrorMsg",        { fg = c.color1 })
hi("WarningMsg",      { fg = c.color3 })
hi("Directory",       { fg = c.color4 })
hi("Title",           { fg = c.color4, bold = true })
hi("NonText",         { fg = c.color8 })
hi("SpecialKey",      { fg = c.color8 })
hi("Conceal",         { fg = c.color8 })
hi("SpellBad",        { undercurl = true, sp = c.color1 })
hi("SpellCap",        { undercurl = true, sp = c.color4 })
hi("SpellLocal",      { undercurl = true, sp = c.color6 })
hi("SpellRare",       { undercurl = true, sp = c.color5 })

-- Diagnostics
hi("DiagnosticError",            { fg = c.color1 })
hi("DiagnosticWarn",             { fg = c.color3 })
hi("DiagnosticInfo",             { fg = c.color4 })
hi("DiagnosticHint",             { fg = c.color6 })
hi("DiagnosticOk",               { fg = c.color2 })
hi("DiagnosticUnderlineError",   { undercurl = true, sp = c.color1 })
hi("DiagnosticUnderlineWarn",    { undercurl = true, sp = c.color3 })
hi("DiagnosticUnderlineInfo",    { undercurl = true, sp = c.color4 })
hi("DiagnosticUnderlineHint",    { undercurl = true, sp = c.color6 })

-- Git (gitsigns etc.)
hi("diffAdded",       { fg = c.color2 })
hi("diffRemoved",     { fg = c.color1 })
hi("diffChanged",     { fg = c.color3 })
hi("GitSignsAdd",     { fg = c.color2 })
hi("GitSignsChange",  { fg = c.color3 })
hi("GitSignsDelete",  { fg = c.color1 })

-- Treesitter
hi("@comment",              { link = "Comment" })
hi("@string",               { link = "String" })
hi("@string.escape",        { fg = c.color6 })
hi("@number",               { link = "Number" })
hi("@float",                { link = "Float" })
hi("@boolean",              { link = "Boolean" })
hi("@keyword",              { link = "Keyword" })
hi("@keyword.function",     { fg = c.color5 })
hi("@keyword.return",       { fg = c.color1 })
hi("@keyword.operator",     { fg = c.color6 })
hi("@function",             { link = "Function" })
hi("@function.builtin",     { fg = c.color6 })
hi("@function.call",        { fg = c.color4 })
hi("@method",               { fg = c.color4 })
hi("@method.call",          { fg = c.color4 })
hi("@constructor",          { fg = c.color3 })
hi("@variable",             { fg = s.foreground })
hi("@variable.builtin",     { fg = c.color5 })
hi("@variable.parameter",   { fg = c.color9 })
hi("@type",                 { link = "Type" })
hi("@type.builtin",         { fg = c.color3 })
hi("@type.qualifier",       { fg = c.color5 })
hi("@property",             { fg = c.color6 })
hi("@field",                { fg = c.color6 })
hi("@punctuation.bracket",  { fg = c.color7 })
hi("@punctuation.delimiter",{ fg = c.color7 })
hi("@punctuation.special",  { fg = c.color6 })
hi("@operator",             { link = "Operator" })
hi("@constant",             { link = "Constant" })
hi("@constant.builtin",     { fg = c.color5 })
hi("@namespace",            { fg = c.color3 })
hi("@include",              { fg = c.color5 })
hi("@tag",                  { fg = c.color1 })
hi("@tag.attribute",        { fg = c.color3 })
hi("@tag.delimiter",        { fg = c.color7 })
hi("@text.title",           { fg = c.color4, bold = true })
hi("@text.uri",             { fg = c.color4, underline = true })
hi("@text.reference",       { fg = c.color6 })
hi("@text.strong",          { bold = true })
hi("@text.emphasis",        { italic = true })
